### ISSUE TITLE
Cutegram [silently] disconnects

### ISSUE THREAD

**Issue by legion1978** [Aseman-Land/Cutegram#128]
After upgrading to 2.5.0 cutegram stops recieving incomming messages (goes idle?). if i restart it, then i get all messages queued. :(

**Comment by realbardia** [comment]
Hi...
Can you send console output? Also do you test logout/login? We made some changes on cutegram login operation in the last weeks. Maybe logout/login fix the problem.

**Comment by legion1978** [comment]
no error output at all. ill try logout/in and see

**Comment by legion1978** [comment]
nope. still same issue. but i think it may have to do with fullscreen apps and the inactive time while running them (gaming and media player)-- can this be checked out? ill keep an eye on this though.

**Comment by legion1978** [comment]
mmm... it seems to be due to inactivity on cutegram. if i stay away too long (say another workspace) then even my messages wont go out (spinning loader) :/

**Comment by jreznik** [comment]
For me this happens when I move between different networks - aka docking station, then wifi with VPN, docking it back again. After that, I got spinning loader too and I have to restart Cutegram to be able to receive/send messages. If you tell me how to provide logs, I'll do it.

**Comment by Dyras** [comment]
Same issue here. It happens when my VPN goes down. Even if it goes back online, Cutegram still seems to be offline.

**Comment by realbardia** [comment]
This issue is fixed on the new libqtelegram-ae. We'll merge it to the master branch soon.

**Comment by Lazza** [comment]
I can confirm that the issue with VPN / IP change in general is still present in version `2.7.0-1`. When will it be fixed?

**Comment by Profpatsch** [comment]
Yep, can confirm. Makes the program pretty much unusable.
